### ISSUE TITLE
Request : Backward compatibility

### ISSUE THREAD

**Issue by AstonBraham** [bopbi/RecyclerParallax#1]
Thanks for this awesome library. It really works fine and smoothly...you are my saviour :) :+1: 
Please Is it possible to make it word on API 10 ?

**Comment by bopbi** [comment]
hmm the reyclerview and appcompat is backward compatible with API 7, i haven't test it yet but the logic for parallax may still work for API 7

**Comment by AstonBraham** [comment]
Okay, :+1: Thank you Mr Bobby, I'll sure check it :)
