### ISSUE TITLE
Similar border bug to ParallaxListView

### ISSUE THREAD

**Issue by DonLiangGit** [bopbi/RecyclerParallax#3]
https://github.com/bopbi/Android-Parallax-ListView-Item/issues/4

i will try to take a look again when having spare time. good work though.

**Comment by bopbi** [comment]
okay thanks for the feedback

**Comment by MiralDesai** [comment]
Is there a solution to this yet? The parallax works, which is nice, but the items are moving and creating gaps between items in the list which is obviously not good. 

Will try an investigate myself when I have time but any chance you guys have found something?

**Comment by MiralDesai** [comment]
Is this still being looked into? I've tried to wrap my head around it and I'm now at a dead end.

**Comment by DonLiangGit** [comment]
@bopbi @MiralDesai https://github.com/yayaa/ParallaxRecyclerView please take a look this `ParallaxImageView.java`

**Comment by bopbi** [comment]
@DonLiangGit thanks for the reference

**Comment by bopbi** [comment]
@MiralDesai @DonLiangGit i have updated the code

basically i try to reduce the usage of a custom view, i hope on my latest code it worked better
